"""Enums for the NFL 2026 pregame operator layer."""

from __future__ import annotations

from enum import Enum


class _StrEnum(str, Enum):
    """Python 3.10 compatible string enum base."""


class PregameEventType(_StrEnum):
    """Append-only event types for the pregame decision log."""

    GAME_CREATED = "GAME_CREATED"
    INITIAL_MARKET_SNAPSHOT = "INITIAL_MARKET_SNAPSHOT"
    MARKET_QUOTE_UPDATED = "MARKET_QUOTE_UPDATED"
    MODEL_SCAN_COMPLETED = "MODEL_SCAN_COMPLETED"
    MODEL_CANDIDATE_CREATED = "MODEL_CANDIDATE_CREATED"
    MODEL_CANDIDATE_BLOCKED = "MODEL_CANDIDATE_BLOCKED"
    RESEARCH_STARTED = "RESEARCH_STARTED"
    RESEARCH_COMPLETED = "RESEARCH_COMPLETED"
    RESEARCH_UPDATED = "RESEARCH_UPDATED"
    INJURY_UPDATED = "INJURY_UPDATED"
    ROSTER_UPDATED = "ROSTER_UPDATED"
    WEATHER_UPDATED = "WEATHER_UPDATED"
    PUBLIC_BETTING_UPDATED = "PUBLIC_BETTING_UPDATED"
    STRUCTURED_MANUAL_EVIDENCE_RECORDED = "STRUCTURED_MANUAL_EVIDENCE_RECORDED"
    STRUCTURED_MANUAL_EVIDENCE_ASSESSMENT_RECORDED = (
        "STRUCTURED_MANUAL_EVIDENCE_ASSESSMENT_RECORDED"
    )
    VARIANT_B_EVIDENCE_LINEAGE_RECORDED = "VARIANT_B_EVIDENCE_LINEAGE_RECORDED"
    FINAL_QUOTE_CAPTURED = "FINAL_QUOTE_CAPTURED"
    FINAL_QUOTE_GATE_EVALUATED = "FINAL_QUOTE_GATE_EVALUATED"
    VARIANT_B_RESEARCH_RECORDED = "VARIANT_B_RESEARCH_RECORDED"
    STRUCTURED_VARIANT_B_AUDIT_RESULT_RECORDED = "STRUCTURED_VARIANT_B_AUDIT_RESULT_RECORDED"
    RESEARCH_APPROVED = "RESEARCH_APPROVED"
    OPERATOR_PICK_APPROVED = "OPERATOR_PICK_APPROVED"
    OPERATOR_PICK_REJECTED = "OPERATOR_PICK_REJECTED"
    OPERATOR_DECISION_RECORDED = "OPERATOR_DECISION_RECORDED"
    CLOSING_QUOTE_CAPTURED = "CLOSING_QUOTE_CAPTURED"
    GAME_SETTLED = "GAME_SETTLED"
    CORRECTION_EVENT = "CORRECTION_EVENT"


class CandidateStatus(_StrEnum):
    """Model-side candidate registry statuses."""

    MODEL_CANDIDATE = "MODEL_CANDIDATE"
    WATCHLIST = "WATCHLIST"
    BLOCKED = "BLOCKED"
    NO_PLAY = "NO_PLAY"
    MISSING_DATA = "MISSING_DATA"


class DecisionLevel(_StrEnum):
    """Separate decision levels; these are not operator verdicts."""

    MODEL_CANDIDATE = "MODEL_CANDIDATE"
    RESEARCH_APPROVED = "RESEARCH_APPROVED"
    FINAL_OPERATOR_PICK = "FINAL_OPERATOR_PICK"


class OperatorVerdict(_StrEnum):
    """Allowed final operator verdict values."""

    APPROVED = "APPROVED"
    APPROVED_REDUCED_STAKE = "APPROVED_REDUCED_STAKE"
    WAIT = "WAIT"
    PASS = "PASS"
    REJECTED_MODEL_DATA = "REJECTED_MODEL_DATA"
    REJECTED_INJURY = "REJECTED_INJURY"
    REJECTED_PRICE = "REJECTED_PRICE"
    REJECTED_LINE_MOVE = "REJECTED_LINE_MOVE"
    REJECTED_MARKET_QUALITY = "REJECTED_MARKET_QUALITY"
    REJECTED_RESEARCH_RISK = "REJECTED_RESEARCH_RISK"
    REJECTED_OPERATOR = "REJECTED_OPERATOR"


class SnapshotKind(_StrEnum):
    """Market snapshot lifecycle labels."""

    INITIAL = "INITIAL"
    CURRENT = "CURRENT"
    FINAL = "FINAL"
    CLOSING = "CLOSING"


class MarketQualityStatus(_StrEnum):
    """Evidence quality status for market data."""

    MARKET_GRADE = "MARKET_GRADE"
    EXECUTABLE_CONFIRMED = "EXECUTABLE_CONFIRMED"
    DISPLAYED_UNVERIFIED = "DISPLAYED_UNVERIFIED"
    STALE = "STALE"
    INCONSISTENT_DISPLAY = "INCONSISTENT_DISPLAY"
    MISSING_TIMESTAMP = "MISSING_TIMESTAMP"
    MISSING_PRICE = "MISSING_PRICE"


class ExecutableStatus(_StrEnum):
    """Execution status is distinct from market evidence quality."""

    CONFIRMED = "CONFIRMED"
    DISPLAYED_ONLY = "DISPLAYED_ONLY"
    UNVERIFIED = "UNVERIFIED"
    NOT_EXECUTABLE = "NOT_EXECUTABLE"
    UNKNOWN = "UNKNOWN"


class MarketType(_StrEnum):
    """Supported market types for basic pregame contracts."""

    SPREAD = "SPREAD"
    TOTAL = "TOTAL"
    MONEYLINE = "MONEYLINE"


class StructuredManualEvidenceCategory(_StrEnum):
    """Supported factual manual-evidence categories."""

    INJURY = "INJURY"
    ROSTER = "ROSTER"
    WEATHER = "WEATHER"
    PUBLIC_BETTING = "PUBLIC_BETTING"


class StructuredManualEvidenceAssessmentStatus(_StrEnum):
    """Research status for an assessment, distinct from Variant B sidecar status."""

    PASS = "PASS"
    WARNING = "WARNING"
    BLOCKING = "BLOCKING"
    PENDING = "PENDING"
    NO_DATA = "NO_DATA"
    NOT_DUE = "NOT_DUE"


class StructuredManualEvidenceAssessorType(_StrEnum):
    """Supported assessors of factual manual evidence."""

    OPERATOR = "OPERATOR"
    GPT_LLM = "GPT_LLM"
    DETERMINISTIC_RULE = "DETERMINISTIC_RULE"
    RESEARCH_PROCESS = "RESEARCH_PROCESS"


class FinalQuoteGateStatus(_StrEnum):
    """Technical result of checking one explicit final market snapshot."""

    FINAL_QUOTE_VALID = "FINAL_QUOTE_VALID"
    FINAL_QUOTE_BLOCKED = "FINAL_QUOTE_BLOCKED"
    FINAL_QUOTE_PENDING = "FINAL_QUOTE_PENDING"


class FinalQuoteGateReason(_StrEnum):
    """Deterministic reasons retained by the final quote gate."""

    CANDIDATE_NOT_FOUND = "CANDIDATE_NOT_FOUND"
    CANDIDATE_BLOCKED = "CANDIDATE_BLOCKED"
    CANDIDATE_NOT_PRODUCTION_ELIGIBLE = "CANDIDATE_NOT_PRODUCTION_ELIGIBLE"
    CANDIDATE_NOT_LATEST = "CANDIDATE_NOT_LATEST"
    FINAL_SNAPSHOT_NOT_FOUND = "FINAL_SNAPSHOT_NOT_FOUND"
    SNAPSHOT_NOT_FINAL = "SNAPSHOT_NOT_FINAL"
    FINAL_SNAPSHOT_NOT_LATEST_FOR_BOOK = "FINAL_SNAPSHOT_NOT_LATEST_FOR_BOOK"
    GAME_ID_MISMATCH = "GAME_ID_MISMATCH"
    SELECTED_SIDE_MISSING = "SELECTED_SIDE_MISSING"
    SELECTED_SIDE_MISMATCH = "SELECTED_SIDE_MISMATCH"
    WRONG_MARKET_TYPE = "WRONG_MARKET_TYPE"
    SPREAD_MISSING = "SPREAD_MISSING"
    PRICE_MISSING = "PRICE_MISSING"
    QUOTE_TIMESTAMP_IN_FUTURE = "QUOTE_TIMESTAMP_IN_FUTURE"
    FINAL_QUOTE_STALE = "FINAL_QUOTE_STALE"
    MARKET_QUALITY_REJECTED = "MARKET_QUALITY_REJECTED"
    EXECUTABLE_STATUS_REJECTED = "EXECUTABLE_STATUS_REJECTED"
    BOOK_REJECTED = "BOOK_REJECTED"
    FINAL_QUOTE_OUTSIDE_FRONTIER = "FINAL_QUOTE_OUTSIDE_FRONTIER"
    FINAL_PRICE_REJECTED = "FINAL_PRICE_REJECTED"
    KEY_NUMBER_LOST = "KEY_NUMBER_LOST"
    NO_CHASE_BLOCK = "NO_CHASE_BLOCK"
    POLICY_INCOMPLETE = "POLICY_INCOMPLETE"
    POLICY_SELECTED_TEAM_MISMATCH = "POLICY_SELECTED_TEAM_MISMATCH"
    POLICY_MARKET_MISMATCH = "POLICY_MARKET_MISMATCH"


class VariantBResearchKind(_StrEnum):
    """Lifecycle kind of a materialized Variant B audit import."""

    FULL_RESEARCH = "FULL_RESEARCH"
    DELTA_UPDATE = "DELTA_UPDATE"
    FINAL_REFRESH = "FINAL_REFRESH"


class VariantBResearchStatus(_StrEnum):
    """Current deterministic state of an imported Variant B audit."""

    PENDING = "PENDING"
    INCOMPLETE = "INCOMPLETE"
    COMPLETE = "COMPLETE"
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
    INVALID = "INVALID"


class VariantBPolicyBuildStatus(_StrEnum):
    """Result status for the fail-closed Variant B policy adapter."""

    BUILT = "BUILT"
    BLOCKED = "BLOCKED"
    INCOMPLETE = "INCOMPLETE"
    INVALID = "INVALID"


class VariantBPolicyBuildReason(_StrEnum):
    """Explicit reasons why a FinalQuotePolicy could not be built."""

    RESEARCH_NOT_FOUND = "RESEARCH_NOT_FOUND"
    RESEARCH_NOT_LATEST = "RESEARCH_NOT_LATEST"
    RESEARCH_NOT_APPROVED = "RESEARCH_NOT_APPROVED"
    RESEARCH_BLOCKED = "RESEARCH_BLOCKED"
    RESEARCH_INCOMPLETE = "RESEARCH_INCOMPLETE"
    CANDIDATE_NOT_FOUND = "CANDIDATE_NOT_FOUND"
    CANDIDATE_NOT_LATEST = "CANDIDATE_NOT_LATEST"
    CANDIDATE_BLOCKED = "CANDIDATE_BLOCKED"
    CANDIDATE_NOT_PRODUCTION_ELIGIBLE = "CANDIDATE_NOT_PRODUCTION_ELIGIBLE"
    CANDIDATE_ID_MISMATCH = "CANDIDATE_ID_MISMATCH"
    GAME_ID_MISMATCH = "GAME_ID_MISMATCH"
    SELECTED_TEAM_MISMATCH = "SELECTED_TEAM_MISMATCH"
    MODEL_VARIANT_MISMATCH = "MODEL_VARIANT_MISMATCH"
    FRONTIER_MISSING = "FRONTIER_MISSING"
    FRONTIER_NOT_STRUCTURED = "FRONTIER_NOT_STRUCTURED"
    SPREAD_FRONTIER_MISSING = "SPREAD_FRONTIER_MISSING"
    SPREAD_FRONTIER_NOT_NUMERIC = "SPREAD_FRONTIER_NOT_NUMERIC"
    PRICE_FRONTIER_MISSING = "PRICE_FRONTIER_MISSING"
    PRICE_FRONTIER_NOT_NUMERIC = "PRICE_FRONTIER_NOT_NUMERIC"
    MARKET_TYPE_MISSING = "MARKET_TYPE_MISSING"
    MARKET_TYPE_UNSUPPORTED = "MARKET_TYPE_UNSUPPORTED"
    NO_CHASE_MISSING = "NO_CHASE_MISSING"
    NO_CHASE_NOT_STRUCTURED = "NO_CHASE_NOT_STRUCTURED"
    NO_CHASE_CONFLICT = "NO_CHASE_CONFLICT"
    KEY_NUMBER_POLICY_MISSING = "KEY_NUMBER_POLICY_MISSING"
    KEY_NUMBER_POLICY_NOT_STRUCTURED = "KEY_NUMBER_POLICY_NOT_STRUCTURED"
    RUNTIME_POLICY_INVALID = "RUNTIME_POLICY_INVALID"
    RUNTIME_POLICY_CONFLICT = "RUNTIME_POLICY_CONFLICT"
    LEGACY_RECOMMENDATION_IGNORED = "LEGACY_RECOMMENDATION_IGNORED"
    POLICY_BUILT = "POLICY_BUILT"
