"""Centralized helpers for filesystem paths used across the project."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

from utils.config import load_settings


def _validate_positive(name: str, value: int) -> int:
    if value <= 0:
        raise ValueError(f"{name} must be a positive integer")
    return value

def core12_path(season: int, week: int) -> Path:
    """Return the path to the Core12 parquet file for a given season/week."""
    return Path(f"data/l4_core12/{season}/{week}.parquet")

def _season_week_path(
    layer: str,
    season: int,
    week: int,
    filename: Optional[str] = None,
    suffix: str = ".parquet",
) -> Path:
    season = _validate_positive("season", season)
    week = _validate_positive("week", week)

    settings = load_settings()
    base_dir = settings.data_root / layer / f"{season}"
    base_dir.mkdir(parents=True, exist_ok=True)

    stem = filename or f"{week}"
    return base_dir / f"{stem}{suffix}"


def path_for(layer: str, season: int, week: int, *, suffix: str = ".parquet") -> Path:
    """Return the canonical path for the given processing layer artifact."""
    return _season_week_path(layer, season, week, suffix=suffix)


def manifest_path(layer: str, season: int, week: int) -> Path:
    """Return the manifest path stored alongside a layer artifact."""
    return _season_week_path(layer, season, week, filename=f"{week}_manifest", suffix=".json")


def l2_audit_path(season: int, week: int) -> Path:
    """Return the JSONL audit path generated by the L2 clean stage."""
    settings = load_settings()
    target = settings.data_root / "l2_audit" / f"{_validate_positive('season', season)}"
    target.mkdir(parents=True, exist_ok=True)
    week_value = _validate_positive("week", week)
    return target / f"{week_value}_audit.jsonl"


def report_path(season: int, week: int) -> Path:
    """Return the path for the markdown report snapshot."""
    settings = load_settings()
    target = settings.data_root / "reports"
    target.mkdir(parents=True, exist_ok=True)
    season_value = _validate_positive("season", season)
    week_value = _validate_positive("week", week)
    return target / f"{season_value}_w{week_value}_summary.md"


def report_manifest_path(season: int, week: int) -> Path:
    """Return the manifest path for the weekly report bundle."""
    settings = load_settings()
    season_value = _validate_positive("season", season)
    week_value = _validate_positive("week", week)
    bundle_dir = settings.data_root / "reports" / f"{season_value}_w{week_value}"
    bundle_dir.mkdir(parents=True, exist_ok=True)
    return bundle_dir / "manifest.json"


def weekly_summary_path(season: int, week: int) -> Path:
    """Return the path for the weekly summary markdown."""
    settings = load_settings()
    season_value = _validate_positive("season", season)
    week_value = _validate_positive("week", week)
    bundle_dir = settings.data_root / "reports" / f"{season_value}_w{week_value}"
    bundle_dir.mkdir(parents=True, exist_ok=True)
    return bundle_dir / "weekly_summary.md"


def _normalize_team_code(team: str) -> str:
    if not team:
        raise ValueError("team code cannot be empty")
    cleaned = re.sub(r"[^A-Za-z0-9]+", "_", str(team).upper()).strip("_")
    if not cleaned:
        raise ValueError(f"Invalid team code: {team!r}")
    return cleaned


def team_reports_dir(season: int, week: int) -> Path:
    settings = load_settings()
    season_value = _validate_positive("season", season)
    week_value = _validate_positive("week", week)
    base_dir = settings.data_root / "reports" / "teams" / f"{season_value}_w{week_value}"
    base_dir.mkdir(parents=True, exist_ok=True)
    return base_dir


def report_assets_dir(season: int, week: int) -> Path:
    """Return the directory where report assets (charts, images) are stored."""
    settings = load_settings()
    reports_root = settings.data_root / "reports"
    reports_root.mkdir(parents=True, exist_ok=True)

    season_value = _validate_positive("season", season)
    week_value = _validate_positive("week", week)

    report_dir = reports_root / f"{season_value}_w{week_value}"
    report_dir.mkdir(parents=True, exist_ok=True)

    assets_dir = report_dir / "assets"
    assets_dir.mkdir(parents=True, exist_ok=True)
    return assets_dir


def team_report_path(season: int, week: int, team: str) -> Path:
    """Return the path for a team-specific markdown report."""
    team_code = _normalize_team_code(team)
    base_dir = team_reports_dir(season, week)
    return base_dir / f"{team_code}.md"


def team_report_assets_dir(season: int, week: int, team: str) -> Path:
    """Return the directory for team report assets."""
    team_code = _normalize_team_code(team)
    base_dir = team_reports_dir(season, week)
    assets_dir = base_dir / "assets"
    assets_team_dir = assets_dir / team_code
    assets_team_dir.mkdir(parents=True, exist_ok=True)
    return assets_team_dir


def team_reports_manifest_path(season: int, week: int) -> Path:
    base_dir = team_reports_dir(season, week)
    return base_dir / "manifest.json"


def comparison_reports_dir(season: int, week: int) -> Path:
    settings = load_settings()
    season_value = _validate_positive("season", season)
    week_value = _validate_positive("week", week)
    base_dir = settings.data_root / "reports" / "comparisons" / f"{season_value}_w{week_value}"
    base_dir.mkdir(parents=True, exist_ok=True)
    return base_dir


def comparison_report_path(season: int, week: int, team_a: str, team_b: str) -> Path:
    """Return the path for a matchup comparison markdown report."""
    team_a_code = _normalize_team_code(team_a)
    team_b_code = _normalize_team_code(team_b)
    base_dir = comparison_reports_dir(season, week)
    return base_dir / f"{team_a_code}_vs_{team_b_code}.md"


def comparison_report_assets_dir(season: int, week: int, team_a: str, team_b: str) -> Path:
    """Return the directory for comparison report assets."""
    team_a_code = _normalize_team_code(team_a)
    team_b_code = _normalize_team_code(team_b)
    base_dir = comparison_reports_dir(season, week)
    assets_dir = base_dir / "assets"
    assets_matchup_dir = assets_dir / f"{team_a_code}_vs_{team_b_code}"
    assets_matchup_dir.mkdir(parents=True, exist_ok=True)
    return assets_matchup_dir


def comparison_reports_manifest_path(season: int, week: int) -> Path:
    base_dir = comparison_reports_dir(season, week)
    return base_dir / "manifest.json"


def rolling_core12_through_path(season: int, through_week: int) -> str:
    """
    Path for cumulative Core12 snapshots.
    Example: data/rolling_core12/2025/through_8.parquet
    """
    return f"data/rolling_core12/{season}/through_{through_week}.parquet"
